#Calculation formulas

out_torque<-function(load,dynamometer_length)
  return(load*dynamometer_length*9.81*0.001)
brake_pow <- function(torque,rpm)
  return(torque*2*3.1415*rpm*0.001/60)
friction_pow <- function(ip,bp)
  return(ip-bp)
bmep <- function(bp, rpm, dia_cyl, stroke_length, cylinders)
  return(((bp * 60 * 2 * 4) / (
    3.1415 * rpm * (dia_cyl^2) * stroke_length * cylinders / (10^9))))
imep <- function(ip, rpm, dia_cyl, stroke_length, cylinders)
  return(((ip * 60 * 2 * 4) / (
    3.1415 * rpm * (dia_cyl^2) * stroke_length * cylinders / (10^9))))
bte <- function(bp, v_fuel, den_fuel, cv_fuel)
  return(bp * 60 / (v_fuel * den_fuel * cv_fuel / 1000))
ite <- function(ip, v_fuel, den_fuel, cv_fuel)
  return(bp * 60 / (v_fuel * den_fuel * cv_fuel / 1000))
mech_eff <- function(bp,ip)
  return(bp/ip)
fuel_flow <- function(v_fuel, den_fuel)
  return(v_fuel * (10^-6) * 60 * den_fuel)
bsfc <- function(fuel_flow,bp)
  return(fuel_flow / (bp / 1000))
isfc <- function(fuel_flow,bp)
  return(fuel_flow/(ip/1000))
vol_eff <- function(air_flow, dia_cyl, stroke_length, rpm, cylinders)
  return(air_flow / (60 * 60) * 2 * 4 * (10^9) * 60 / (1.17 * 3.1415 * (dia_cyl^2) * stroke_length * rpm * cylinders))
ehaust_loss <- function(v_water_cal, fuel_flow, cv_fuel, t3, t4, t5, t6)
  return(v_water_cal * 4.186 * (t4 - t3) * (t5 - 29) / (fuel_flow * cv_fuel * (t5 - t6)))
heat_loss <- function(v_water_engine, fuel_flow, cv_fuel, t1, t2)
  return(v_water_engine * 4.186 * (t2 - t1) / (fuel_flow * cv_fuel))